### PR TITLE
Add tools/whitespace.txt

### PR DESCRIPTION
**Pull request by saneyuki**
This is something like https://github.com/google/skia/blob/master/whitespace.txt

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 55c6914689f10e800fd567caf4abc5954ca738fe has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 55c6914689f10e800fd567caf4abc5954ca738fe has been merged into the auto branch 1a7984166d0e9c7fae0e315b2db59d3952836ca8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/232666572?utm_source=github_status&utm_medium=notification)

**Pull request merged**
