### PR TITLE
Update to 5.7

### LINKED ISSUE #35: Update tslint 5.6 => 5.7
https://github.com/palantir/tslint/releases/tag/5.7.0

### PR DESCRIPTION
**Pull request by nekoya**
fix #35

### CODE REVIEW

**Comment by kanufy** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2b4873ee8db6a161c2e79fb4e95b0a1cdf49912e has been approved by `kanufy`

**Comment by popuko** [comment]
:hourglass: 2b4873ee8db6a161c2e79fb4e95b0a1cdf49912e has been merged into the auto branch 2b7688069eaee13c14ea0a78d7aa76e50db865f8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/269073756?utm_source=github_status&utm_medium=notification)

**Pull request merged**
