### PR TITLE
Update tslint

### PR DESCRIPTION
**Pull request by kanufy**
fix: #31

### CODE REVIEW

**Comment by himu62** [comment]
assignされてないけど良さそう
OWNERじゃないので @nekoya さんにおまかせします

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 330f944293ce41ac4820485f398058545505ce97 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 330f944293ce41ac4820485f398058545505ce97 has been merged into the auto branch 6b4bd5180788d429d653f2aa8dada86b6e4d3399

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/265487431?utm_source=github_status&utm_medium=notification)

**Pull request merged**
