### PR TITLE
Import basic rules from our internal repository

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d5a705680f870cde2b59963651837b67f8b6ee99 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: d5a705680f870cde2b59963651837b67f8b6ee99 has been merged into the auto branch 0c9b24be98209233001bcb38da9bb288b06042b9

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/232695633?utm_source=github_status&utm_medium=notification)

**Pull request merged**
