### PR TITLE
Add more documentation to README

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2c3eedfa979061c95c2b2ce62ae4aa93ac6d0423 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 2c3eedfa979061c95c2b2ce62ae4aa93ac6d0423 has been merged into the auto branch 64d51b3e2302fcc9c17b6b411fbf7c0075db70e5

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/233909007?utm_source=github_status&utm_medium=notification)

**Pull request merged**
