### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kanufy**
積み残していたのでそろそろあげようかと。

## typescript
fixed: #28 

## tslint
fixed: #29

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit a0e4af906d1e1e4cabfcade34e4f885a5a9904b1 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: a0e4af906d1e1e4cabfcade34e4f885a5a9904b1 has been merged into the auto branch ae13c33db202940a322c85761ab199513eda2e55

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/259264657?utm_source=github_status&utm_medium=notification)

**Pull request merged**
