### PR TITLE
Update tslint to v5.3

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/voyagegroup/tslint-config-fluct/issues/11

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit d72f6fe04bb012c0e6300216f538a690528ac934 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: d72f6fe04bb012c0e6300216f538a690528ac934 has been merged into the auto branch 27e5703e4cdec5e65a29269c7d16f4ac7d7ff195

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/235496300?utm_source=github_status&utm_medium=notification)

**Pull request merged**
