### PR TITLE
Setup 'npm test' to run tslint

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 5168133a4aa11e0c2a45098d2eb903952d8d82b0 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 5168133a4aa11e0c2a45098d2eb903952d8d82b0 has been merged into the auto branch c9cce2af41c26e660729dfc76dbee49f244a8225

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/232679501?utm_source=github_status&utm_medium=notification)

**Pull request merged**
