### PR TITLE
Register new owners

### PR DESCRIPTION
**Pull request by nekoya**
welcome guys.

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 17c6e59431ce16beb99fdf6c2bd49828a90883cb has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 17c6e59431ce16beb99fdf6c2bd49828a90883cb has been merged into the auto branch 1c28e63749816c92754e3ae3972fa54d983f3a94

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/265491853?utm_source=github_status&utm_medium=notification)

**Pull request merged**
