### PR TITLE
Fix the file extension for the setup instruction

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c25aa27c5d35044bc1888fc1d35d0bca0ec65eef has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: c25aa27c5d35044bc1888fc1d35d0bca0ec65eef has been merged into the auto branch 3ce254129e16119901c9f454690d3d926ef25156

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/tslint-config-fluct/builds/297773590?utm_source=github_status&utm_medium=notification)

**Pull request merged**
